import type {
  Profile,
  AccessRequest,
  Question,
  QuestionAttempt,
  MockExam,
  MockExamQuestion,
  MockAnswer,
  AiConversation,
  AiMessage,
} from "@/types/database";

export const STUDENT_ID = "dev-student-00000000-0000-0000-0000-000000000001";
export const ADMIN_ID = "dev-admin-000000-0000-0000-0000-000000000002";

// ── Profiles ────────────────────────────────────────────────────────────────

export const MOCK_PROFILES: Profile[] = [
  {
    id: STUDENT_ID,
    full_name: "Dev Student",
    email: "dev-student@localhost",
    phone: null,
    role: "student",
    target_exam: "USMLE Step 1",
    exam_date: "2027-06-15",
    access_status: "active",
    access_expires_at: null,
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
  },
  {
    id: ADMIN_ID,
    full_name: "Dev Admin",
    email: "dev-admin@localhost",
    phone: null,
    role: "admin",
    target_exam: null,
    exam_date: null,
    access_status: "active",
    access_expires_at: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "student-2",
    full_name: "Aisha Al-Rashid",
    email: "aisha@example.com",
    phone: "+966501234567",
    role: "student",
    target_exam: "USMLE Step 2",
    exam_date: "2027-09-20",
    access_status: "active",
    access_expires_at: null,
    created_at: "2024-02-01T08:00:00Z",
    updated_at: "2024-02-01T08:00:00Z",
  },
  {
    id: "student-3",
    full_name: "Omar Khalil",
    email: "omar@example.com",
    phone: null,
    role: "student",
    target_exam: "USMLE Step 1",
    exam_date: null,
    access_status: "pending",
    access_expires_at: null,
    created_at: "2024-02-15T12:00:00Z",
    updated_at: "2024-02-15T12:00:00Z",
  },
  {
    id: "student-4",
    full_name: "Fatima Hassan",
    email: "fatima@example.com",
    phone: "+96656789012",
    role: "student",
    target_exam: "PLAB",
    exam_date: "2027-11-01",
    access_status: "active",
    access_expires_at: "2027-12-31T00:00:00Z",
    created_at: "2024-03-01T09:00:00Z",
    updated_at: "2024-03-01T09:00:00Z",
  },
  {
    id: "student-5",
    full_name: "Yusuf Al-Amin",
    email: "yusuf@example.com",
    phone: null,
    role: "student",
    target_exam: "USMLE Step 1",
    exam_date: null,
    access_status: "expired",
    access_expires_at: "2024-12-31T00:00:00Z",
    created_at: "2024-01-20T14:00:00Z",
    updated_at: "2024-01-20T14:00:00Z",
  },
  {
    id: "student-6",
    full_name: "Nour Ibrahim",
    email: "nour@example.com",
    phone: "+966512345678",
    role: "student",
    target_exam: "USMLE Step 2",
    exam_date: "2027-08-10",
    access_status: "active",
    access_expires_at: null,
    created_at: "2024-03-10T11:00:00Z",
    updated_at: "2024-03-10T11:00:00Z",
  },
];

// ── Access Requests ──────────────────────────────────────────────────────────

export const MOCK_ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: "req-1",
    full_name: "Sara Al-Mutairi",
    email: "sara.m@example.com",
    phone: "+966507654321",
    target_exam: "USMLE Step 1",
    expected_exam_date: "2027-07-01",
    notes: "I'm a 5th-year medical student preparing for Step 1.",
    status: "new",
    created_at: "2026-09-25T09:00:00Z",
    updated_at: "2026-09-25T09:00:00Z",
  },
  {
    id: "req-2",
    full_name: "Khalid Al-Otaibi",
    email: "khalid.o@example.com",
    phone: "+966551234567",
    target_exam: "PLAB",
    expected_exam_date: "2027-10-15",
    notes: null,
    status: "contacted",
    created_at: "2026-09-20T14:30:00Z",
    updated_at: "2026-09-22T10:00:00Z",
  },
  {
    id: "req-3",
    full_name: "Mona Saleh",
    email: "mona.s@example.com",
    phone: null,
    target_exam: "USMLE Step 2",
    expected_exam_date: null,
    notes: "Referred by a friend who is already using the platform.",
    status: "paid",
    created_at: "2026-09-15T16:00:00Z",
    updated_at: "2026-09-28T08:00:00Z",
  },
];

// ── Questions (20 published) ─────────────────────────────────────────────────

export const MOCK_QUESTIONS: Question[] = [
  // ── Cardiology (8) ──────────────────────────────────────────────────────
  {
    id: "q-1",
    question_text:
      "A 58-year-old man presents with crushing chest pain radiating to the left arm. ECG shows ST-segment elevation in leads II, III, and aVF. Which coronary artery is most likely occluded?",
    option_a: "Left anterior descending artery",
    option_b: "Right coronary artery",
    option_c: "Left circumflex artery",
    option_d: "Left main coronary artery",
    correct_answer: "B",
    justification: "ST elevation in II, III, aVF indicates inferior MI, most commonly caused by RCA occlusion.",
    explanation_a: "LAD occlusion causes anterior MI with ST elevation in V1–V4.",
    explanation_b: "Correct. The RCA supplies the inferior wall of the left ventricle in most individuals.",
    explanation_c: "LCx occlusion causes lateral MI with changes in I, aVL, V5–V6.",
    explanation_d: "LMCA occlusion causes massive anterior/lateral MI.",
    exam: "USMLE Step 1",
    category: "Cardiology",
    topic: "Coronary Artery Disease",
    subtopic: "STEMI",
    difficulty: "medium",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-2",
    question_text:
      "A 65-year-old woman with hypertension and diabetes develops acute chest pain. Which drug provides the most rapid relief of an acute anginal episode?",
    option_a: "Aspirin",
    option_b: "Amlodipine",
    option_c: "Sublingual nitroglycerin",
    option_d: "Metoprolol",
    correct_answer: "C",
    justification: "Sublingual nitroglycerin causes rapid venodilation and relieves acute angina within minutes.",
    explanation_a: "Aspirin prevents platelet aggregation but does not relieve acute symptoms.",
    explanation_b: "Amlodipine prevents angina chronically but acts too slowly for acute episodes.",
    explanation_c: "Correct. SL nitroglycerin is the drug of choice for acute angina relief.",
    explanation_d: "Beta-blockers reduce anginal frequency but are not for acute relief.",
    exam: "USMLE Step 1",
    category: "Cardiology",
    topic: "Coronary Artery Disease",
    subtopic: "Stable Angina",
    difficulty: "easy",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-3",
    question_text:
      "Which medication has the most robust mortality benefit in heart failure with reduced ejection fraction (HFrEF)?",
    option_a: "Digoxin",
    option_b: "ACE inhibitor",
    option_c: "Loop diuretics",
    option_d: "Spironolactone",
    correct_answer: "B",
    justification: "ACE inhibitors reduce afterload and have the strongest mortality evidence in HFrEF.",
    explanation_a: "Digoxin reduces hospitalizations but does not reduce mortality.",
    explanation_b: "Correct. ACE inhibitors (e.g., enalapril) are first-line with proven mortality benefit.",
    explanation_c: "Loop diuretics relieve congestion but have no mortality benefit.",
    explanation_d: "Aldosterone antagonists are added as second-line therapy.",
    exam: "USMLE Step 1",
    category: "Cardiology",
    topic: "Heart Failure",
    subtopic: "HFrEF",
    difficulty: "easy",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-4",
    question_text:
      "A 70-year-old man develops atrial fibrillation at 155 bpm. He is hemodynamically stable. What is the most appropriate initial management?",
    option_a: "Immediate synchronized DC cardioversion",
    option_b: "IV amiodarone for rhythm control",
    option_c: "Rate control with IV metoprolol",
    option_d: "Oral warfarin",
    correct_answer: "C",
    justification: "In hemodynamically stable AF, rate control is the priority before rhythm control.",
    explanation_a: "DC cardioversion is reserved for hemodynamically unstable patients.",
    explanation_b: "Amiodarone achieves rhythm control but is not the first step.",
    explanation_c: "Correct. Rate control with beta-blockers is the initial priority in stable patients.",
    explanation_d: "Anticoagulation is important for stroke prevention but not for acute rate management.",
    exam: "USMLE Step 2",
    category: "Cardiology",
    topic: "Arrhythmias",
    subtopic: "Atrial Fibrillation",
    difficulty: "medium",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-5",
    question_text:
      "Which of the following is an absolute contraindication to thrombolytic therapy in acute STEMI?",
    option_a: "Age > 75 years",
    option_b: "Prior ischemic stroke 2 years ago",
    option_c: "Hemorrhagic stroke 4 weeks ago",
    option_d: "Uncontrolled hypertension (180/100)",
    correct_answer: "C",
    justification: "Prior intracranial hemorrhage at any time is an absolute contraindication to thrombolytics.",
    explanation_a: "Age > 75 is a relative, not absolute, contraindication.",
    explanation_b: "Ischemic stroke > 3 months ago is a relative contraindication.",
    explanation_c: "Correct. Hemorrhagic stroke is an absolute contraindication due to rebleeding risk.",
    explanation_d: "Severe uncontrolled hypertension is a relative contraindication.",
    exam: "USMLE Step 2",
    category: "Cardiology",
    topic: "Coronary Artery Disease",
    subtopic: "STEMI Management",
    difficulty: "medium",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-6",
    question_text:
      "A patient presents with muffled heart sounds, hypotension, and jugular venous distension. Which condition does this triad most suggest?",
    option_a: "Tension pneumothorax",
    option_b: "Cardiac tamponade",
    option_c: "Massive pulmonary embolism",
    option_d: "Aortic stenosis",
    correct_answer: "B",
    justification: "Beck's triad (muffled heart sounds, hypotension, JVD) is pathognomonic for cardiac tamponade.",
    explanation_a: "Tension pneumothorax presents with absent breath sounds and tracheal deviation.",
    explanation_b: "Correct. Beck's triad is classic for pericardial tamponade.",
    explanation_c: "Massive PE presents with hypotension and JVD but not muffled heart sounds.",
    explanation_d: "Aortic stenosis presents with a systolic crescendo-decrescendo murmur.",
    exam: "USMLE Step 1",
    category: "Cardiology",
    topic: "Pericardial Disease",
    subtopic: "Cardiac Tamponade",
    difficulty: "easy",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-7",
    question_text:
      "Which valvular lesion produces a low-pitched diastolic rumble best heard at the cardiac apex with the patient in the left lateral decubitus position?",
    option_a: "Aortic regurgitation",
    option_b: "Mitral stenosis",
    option_c: "Tricuspid stenosis",
    option_d: "Pulmonary regurgitation",
    correct_answer: "B",
    justification: "Mitral stenosis produces a diastolic rumble at the apex with an opening snap.",
    explanation_a: "Aortic regurgitation produces a high-pitched early diastolic murmur at the left sternal border.",
    explanation_b: "Correct. Mitral stenosis causes a low diastolic rumble at the apex.",
    explanation_c: "Tricuspid stenosis is rare and best heard at the left lower sternal border.",
    explanation_d: "Pulmonary regurgitation (Graham Steell) is heard at the left sternal border.",
    exam: "USMLE Step 1",
    category: "Cardiology",
    topic: "Valvular Heart Disease",
    subtopic: "Mitral Stenosis",
    difficulty: "medium",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-8",
    question_text:
      "A 72-year-old woman on warfarin for atrial fibrillation has an INR of 9.0 with no signs of bleeding. What is the most appropriate management?",
    option_a: "Administer IV vitamin K",
    option_b: "Hold warfarin and recheck INR in 24 hours",
    option_c: "Give fresh frozen plasma immediately",
    option_d: "Continue warfarin at the same dose",
    correct_answer: "B",
    justification: "For asymptomatic supratherapeutic INR 5–10, holding warfarin and monitoring is appropriate.",
    explanation_a: "IV vitamin K is indicated for INR > 10 or for significant bleeding.",
    explanation_b: "Correct. Holding warfarin and rechecking is the appropriate step for INR 5–10 without bleeding.",
    explanation_c: "FFP is reserved for life-threatening bleeding requiring immediate reversal.",
    explanation_d: "Continuing the same dose would further elevate the INR.",
    exam: "USMLE Step 2",
    category: "Cardiology",
    topic: "Anticoagulation",
    subtopic: "Warfarin Management",
    difficulty: "medium",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // ── Pharmacology (6) ────────────────────────────────────────────────────
  {
    id: "q-9",
    question_text: "Penicillin exerts its antibacterial effect by which mechanism?",
    option_a: "Inhibiting protein synthesis at the 30S ribosomal subunit",
    option_b: "Inhibiting cell wall synthesis by binding penicillin-binding proteins (PBPs)",
    option_c: "Disrupting the bacterial cell membrane",
    option_d: "Inhibiting DNA gyrase",
    correct_answer: "B",
    justification: "Penicillins bind PBPs and inhibit transpeptidation, preventing peptidoglycan cross-linking.",
    explanation_a: "30S subunit inhibition is the mechanism of aminoglycosides and tetracyclines.",
    explanation_b: "Correct. Penicillin blocks PBPs to inhibit cell wall synthesis.",
    explanation_c: "Cell membrane disruption is the mechanism of polymyxins.",
    explanation_d: "DNA gyrase inhibition is the mechanism of fluoroquinolones.",
    exam: "USMLE Step 1",
    category: "Pharmacology",
    topic: "Antibiotics",
    subtopic: "Beta-Lactams",
    difficulty: "easy",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-10",
    question_text:
      "A patient on statin therapy presents with severe myalgia, dark urine, and a CK of 52,000 U/L. What is the most serious concern?",
    option_a: "Statin-induced hepatotoxicity",
    option_b: "Rhabdomyolysis",
    option_c: "Peripheral neuropathy",
    option_d: "QT prolongation",
    correct_answer: "B",
    justification:
      "Markedly elevated CK with myoglobinuria constitutes rhabdomyolysis, the most serious statin complication.",
    explanation_a: "Hepatotoxicity would present with elevated transaminases, not CK and myoglobinuria.",
    explanation_b: "Correct. Rhabdomyolysis requires immediate statin discontinuation.",
    explanation_c: "Peripheral neuropathy is not a recognized serious statin complication.",
    explanation_d: "QT prolongation is not associated with statin use.",
    exam: "USMLE Step 2",
    category: "Pharmacology",
    topic: "Lipid-Lowering Agents",
    subtopic: "Statins",
    difficulty: "easy",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-11",
    question_text:
      "Which antiarrhythmic drug is most strongly associated with QT prolongation and torsades de pointes?",
    option_a: "Adenosine",
    option_b: "Lidocaine",
    option_c: "Sotalol",
    option_d: "Verapamil",
    correct_answer: "C",
    justification: "Sotalol (class III) prolongs the QT interval via K+ channel blockade and can precipitate torsades.",
    explanation_a: "Adenosine has a very short half-life and does not prolong QT.",
    explanation_b: "Lidocaine (class Ib) shortens action potential duration.",
    explanation_c: "Correct. Sotalol prolongs repolarization and is a well-known cause of torsades de pointes.",
    explanation_d: "Verapamil affects AV nodal conduction but not QT significantly.",
    exam: "USMLE Step 1",
    category: "Pharmacology",
    topic: "Antiarrhythmics",
    subtopic: "Class III Agents",
    difficulty: "medium",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-12",
    question_text:
      "A patient receiving methotrexate for rheumatoid arthritis develops signs of folate deficiency. Which agent should be co-prescribed to prevent this toxicity?",
    option_a: "Vitamin B12 (cyanocobalamin)",
    option_b: "Leucovorin (folinic acid)",
    option_c: "Riboflavin (vitamin B2)",
    option_d: "Pyridoxine (vitamin B6)",
    correct_answer: "B",
    justification:
      "Leucovorin is a reduced folate that bypasses DHFR inhibition by methotrexate, rescuing normal cells.",
    explanation_a: "Vitamin B12 is not effective for methotrexate-induced folate deficiency.",
    explanation_b: "Correct. Leucovorin rescues host cells from methotrexate toxicity.",
    explanation_c: "Riboflavin is unrelated to folate metabolism.",
    explanation_d: "Pyridoxine is used to prevent isoniazid-induced neuropathy.",
    exam: "USMLE Step 1",
    category: "Pharmacology",
    topic: "Antimetabolites",
    subtopic: "Methotrexate Toxicity",
    difficulty: "medium",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-13",
    question_text:
      "A 32-year-old woman with asthma requires treatment for newly diagnosed hypertension. Which drug class is contraindicated?",
    option_a: "ACE inhibitors",
    option_b: "Thiazide diuretics",
    option_c: "Non-selective beta-blockers",
    option_d: "Calcium channel blockers",
    correct_answer: "C",
    justification:
      "Non-selective beta-blockers block bronchial beta-2 receptors, precipitating bronchospasm in asthmatics.",
    explanation_a: "ACE inhibitors cause cough but are not contraindicated in asthma.",
    explanation_b: "Thiazides are safe in asthma.",
    explanation_c: "Correct. Non-selective beta-blockers (e.g., propranolol) are contraindicated in asthma.",
    explanation_d: "Calcium channel blockers are safe and often used in asthma with hypertension.",
    exam: "USMLE Step 2",
    category: "Pharmacology",
    topic: "Antihypertensives",
    subtopic: "Beta-Blockers",
    difficulty: "easy",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-14",
    question_text: "What is the primary mechanism of action of thiazide diuretics?",
    option_a: "Inhibit Na+/K+/2Cl– cotransporter in the thick ascending limb of Henle",
    option_b: "Block aldosterone receptors in the collecting duct",
    option_c: "Inhibit Na+/Cl– cotransporter in the distal convoluted tubule",
    option_d: "Inhibit carbonic anhydrase in the proximal tubule",
    correct_answer: "C",
    justification: "Thiazides inhibit NCC (Na-Cl cotransporter) in the DCT, reducing sodium reabsorption.",
    explanation_a: "NKCC2 inhibition is the mechanism of loop diuretics such as furosemide.",
    explanation_b: "Aldosterone antagonism is the mechanism of spironolactone/eplerenone.",
    explanation_c: "Correct. Thiazides block NCC in the DCT.",
    explanation_d: "Carbonic anhydrase inhibition is the mechanism of acetazolamide.",
    exam: "USMLE Step 1",
    category: "Pharmacology",
    topic: "Diuretics",
    subtopic: "Thiazide Diuretics",
    difficulty: "medium",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // ── Anatomy (6) ─────────────────────────────────────────────────────────
  {
    id: "q-15",
    question_text:
      "A 25-year-old sustains an anterior shoulder dislocation. Examination shows loss of sensation over the lateral shoulder (regimental badge area). Which nerve is most likely injured?",
    option_a: "Musculocutaneous nerve",
    option_b: "Radial nerve",
    option_c: "Axillary nerve",
    option_d: "Suprascapular nerve",
    correct_answer: "C",
    justification:
      "The axillary nerve winds around the surgical neck of the humerus and is commonly injured in anterior shoulder dislocation.",
    explanation_a: "Musculocutaneous nerve injury causes elbow flexion weakness.",
    explanation_b: "Radial nerve injury at the spiral groove causes wrist drop.",
    explanation_c: "Correct. Axillary nerve injury is the most common neurological complication of shoulder dislocation.",
    explanation_d: "Suprascapular nerve injury causes weakness of abduction and external rotation.",
    exam: "USMLE Step 1",
    category: "Anatomy",
    topic: "Upper Limb",
    subtopic: "Brachial Plexus Injuries",
    difficulty: "medium",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-16",
    question_text: "Which dermatome level corresponds to the nipple?",
    option_a: "T2",
    option_b: "T4",
    option_c: "T6",
    option_d: "T8",
    correct_answer: "B",
    justification: "T4 is the classic dermatome landmark for the nipple level.",
    explanation_a: "T2 supplies the medial upper arm.",
    explanation_b: "Correct. T4 = nipple level is a key anatomical landmark.",
    explanation_c: "T6 is approximately at the xiphoid process.",
    explanation_d: "T8 is below the costal margin.",
    exam: "USMLE Step 1",
    category: "Anatomy",
    topic: "Surface Anatomy",
    subtopic: "Dermatomes",
    difficulty: "easy",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-17",
    question_text: "Which nerve is compressed in carpal tunnel syndrome?",
    option_a: "Radial nerve",
    option_b: "Ulnar nerve",
    option_c: "Median nerve",
    option_d: "Anterior interosseous nerve",
    correct_answer: "C",
    justification: "The median nerve passes through the carpal tunnel and is compressed, causing CTS.",
    explanation_a: "The radial nerve does not pass through the carpal tunnel.",
    explanation_b: "The ulnar nerve passes through Guyon's canal lateral to the carpal tunnel.",
    explanation_c: "Correct. The median nerve is compressed under the flexor retinaculum.",
    explanation_d: "The AIN is a deep branch of the median nerve, not the primary nerve affected in CTS.",
    exam: "USMLE Step 1",
    category: "Anatomy",
    topic: "Upper Limb",
    subtopic: "Peripheral Nerve Entrapment",
    difficulty: "easy",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-18",
    question_text:
      "A neonate is born with the arm held in adduction and internal rotation with the forearm pronated (waiter's tip position). Which nerve roots are damaged?",
    option_a: "C8–T1",
    option_b: "C5–C6",
    option_c: "C7–C8",
    option_d: "C6–C7",
    correct_answer: "B",
    justification:
      "Erb's palsy involves upper brachial plexus roots C5–C6, classically from excessive lateral neck traction during delivery.",
    explanation_a: "C8–T1 injury causes Klumpke's palsy (claw hand, Horner's).",
    explanation_b: "Correct. Erb's palsy (C5–C6) presents as the waiter's tip deformity.",
    explanation_c: "C7–C8 injury would affect wrist and finger extensors.",
    explanation_d: "C6–C7 injury would not produce the classic Erb's posture.",
    exam: "USMLE Step 1",
    category: "Anatomy",
    topic: "Upper Limb",
    subtopic: "Brachial Plexus Injuries",
    difficulty: "medium",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-19",
    question_text:
      "The contents of the femoral triangle from lateral to medial are remembered by the mnemonic NAVY. What is the correct lateral-to-medial order?",
    option_a: "Vein, Artery, Nerve",
    option_b: "Nerve, Artery, Vein",
    option_c: "Artery, Vein, Nerve",
    option_d: "Nerve, Vein, Artery",
    correct_answer: "B",
    justification: "NAVY: Nerve (lateral), Artery, Vein, emptY space (lymphatics).",
    explanation_a: "The vein is medial to the artery, not lateral.",
    explanation_b: "Correct. NAV(Y): Nerve lateral, then Artery, then Vein medially.",
    explanation_c: "The artery is in the middle, not the most lateral structure.",
    explanation_d: "The nerve is lateral, not medial to the artery.",
    exam: "USMLE Step 1",
    category: "Anatomy",
    topic: "Lower Limb",
    subtopic: "Femoral Triangle",
    difficulty: "easy",
    year: 2022,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "q-20",
    question_text: "Which artery predominantly supplies the sinoatrial (SA) node in the majority of individuals?",
    option_a: "Left anterior descending artery",
    option_b: "Left circumflex artery",
    option_c: "Right coronary artery",
    option_d: "Posterior descending artery",
    correct_answer: "C",
    justification: "In approximately 60% of individuals, the SA nodal artery arises from the RCA.",
    explanation_a: "The LAD supplies the anterior interventricular septum and bundle of His.",
    explanation_b: "The LCx supplies the SA node in about 40% of individuals (left-dominant circulation).",
    explanation_c: "Correct. The RCA supplies the SA node in ~60% of people (right-dominant).",
    explanation_d: "The PDA supplies the inferior interventricular septum and AV node.",
    exam: "USMLE Step 1",
    category: "Anatomy",
    topic: "Cardiac Anatomy",
    subtopic: "Coronary Circulation",
    difficulty: "medium",
    year: 2023,
    source: "Mock Bank",
    status: "published",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ── Question Attempts (for the student) ──────────────────────────────────────

export const MOCK_QUESTION_ATTEMPTS: QuestionAttempt[] = [
  { id: "att-1",  user_id: STUDENT_ID, question_id: "q-1",  selected_answer: "B", is_correct: true,  attempted_at: "2026-09-01T10:00:00Z" },
  { id: "att-2",  user_id: STUDENT_ID, question_id: "q-2",  selected_answer: "C", is_correct: true,  attempted_at: "2026-09-01T10:05:00Z" },
  { id: "att-3",  user_id: STUDENT_ID, question_id: "q-3",  selected_answer: "B", is_correct: true,  attempted_at: "2026-09-02T09:00:00Z" },
  { id: "att-4",  user_id: STUDENT_ID, question_id: "q-4",  selected_answer: "A", is_correct: false, attempted_at: "2026-09-02T09:10:00Z" },
  { id: "att-5",  user_id: STUDENT_ID, question_id: "q-5",  selected_answer: "C", is_correct: true,  attempted_at: "2026-09-03T11:00:00Z" },
  { id: "att-6",  user_id: STUDENT_ID, question_id: "q-6",  selected_answer: "B", is_correct: true,  attempted_at: "2026-09-04T14:00:00Z" },
  { id: "att-7",  user_id: STUDENT_ID, question_id: "q-7",  selected_answer: "A", is_correct: false, attempted_at: "2026-09-05T10:00:00Z" },
  { id: "att-8",  user_id: STUDENT_ID, question_id: "q-8",  selected_answer: "B", is_correct: true,  attempted_at: "2026-09-06T09:30:00Z" },
  { id: "att-9",  user_id: STUDENT_ID, question_id: "q-9",  selected_answer: "B", is_correct: true,  attempted_at: "2026-09-07T10:00:00Z" },
  { id: "att-10", user_id: STUDENT_ID, question_id: "q-10", selected_answer: "B", is_correct: true,  attempted_at: "2026-09-08T11:00:00Z" },
  { id: "att-11", user_id: STUDENT_ID, question_id: "q-11", selected_answer: "A", is_correct: false, attempted_at: "2026-09-09T09:00:00Z" },
  { id: "att-12", user_id: STUDENT_ID, question_id: "q-12", selected_answer: "B", is_correct: true,  attempted_at: "2026-09-10T10:30:00Z" },
  { id: "att-13", user_id: STUDENT_ID, question_id: "q-13", selected_answer: "C", is_correct: true,  attempted_at: "2026-09-20T08:00:00Z" },
  { id: "att-14", user_id: STUDENT_ID, question_id: "q-15", selected_answer: "C", is_correct: true,  attempted_at: "2026-09-25T09:00:00Z" },
  { id: "att-15", user_id: STUDENT_ID, question_id: "q-16", selected_answer: "B", is_correct: true,  attempted_at: "2026-09-27T10:00:00Z" },
];

// ── Mock Exams ────────────────────────────────────────────────────────────────

export const MOCK_EXAMS: MockExam[] = [
  {
    id: "me-1",
    user_id: STUDENT_ID,
    exam_name: "USMLE Step 1",
    started_at: "2026-09-15T09:00:00Z",
    completed_at: "2026-09-15T10:45:00Z",
    question_count: 10,
    score: 7,
    percentage: 70.0,
    duration_seconds: 6300,
  },
  {
    id: "me-2",
    user_id: STUDENT_ID,
    exam_name: null,
    started_at: "2026-09-28T14:00:00Z",
    completed_at: null,
    question_count: 10,
    score: null,
    percentage: null,
    duration_seconds: null,
  },
];

// ── Mock Exam Questions ───────────────────────────────────────────────────────

const ME1_QUESTION_IDS = ["q-1","q-2","q-3","q-4","q-5","q-6","q-7","q-8","q-9","q-10"];
const ME2_QUESTION_IDS = ["q-11","q-12","q-13","q-14","q-15","q-16","q-17","q-18","q-19","q-20"];

export const MOCK_EXAM_QUESTIONS: MockExamQuestion[] = [
  ...ME1_QUESTION_IDS.map((qid, i) => ({
    id: `meq-1-${i + 1}`,
    mock_exam_id: "me-1",
    question_id: qid,
    position: i + 1,
    flagged: i === 3, // flag question 4
  })),
  ...ME2_QUESTION_IDS.map((qid, i) => ({
    id: `meq-2-${i + 1}`,
    mock_exam_id: "me-2",
    question_id: qid,
    position: i + 1,
    flagged: false,
  })),
];

// ── Mock Answers (completed exam me-1) ───────────────────────────────────────

const ME1_ANSWERS: Record<string, { answer: "A"|"B"|"C"|"D"; correct: boolean }> = {
  "q-1":  { answer: "B", correct: true  },
  "q-2":  { answer: "C", correct: true  },
  "q-3":  { answer: "B", correct: true  },
  "q-4":  { answer: "A", correct: false },
  "q-5":  { answer: "C", correct: true  },
  "q-6":  { answer: "B", correct: true  },
  "q-7":  { answer: "A", correct: false },
  "q-8":  { answer: "B", correct: true  },
  "q-9":  { answer: "B", correct: true  },
  "q-10": { answer: "D", correct: false },
};

export const MOCK_ANSWERS: MockAnswer[] = ME1_QUESTION_IDS.map((qid) => ({
  id: `ma-${qid}`,
  mock_exam_id: "me-1",
  question_id: qid,
  selected_answer: ME1_ANSWERS[qid].answer,
  is_correct: ME1_ANSWERS[qid].correct,
}));

// ── AI Conversations ──────────────────────────────────────────────────────────

export const MOCK_AI_CONVERSATIONS: AiConversation[] = [
  {
    id: "conv-1",
    user_id: STUDENT_ID,
    title: "Understanding the cardiac cycle",
    question_id: "q-1",
    created_at: "2026-09-20T10:00:00Z",
    updated_at: "2026-09-20T10:05:00Z",
  },
  {
    id: "conv-2",
    user_id: STUDENT_ID,
    title: "Mechanism of beta-lactam antibiotics",
    question_id: "q-9",
    created_at: "2026-09-22T14:00:00Z",
    updated_at: "2026-09-22T14:08:00Z",
  },
];

// ── AI Messages ───────────────────────────────────────────────────────────────

export const MOCK_AI_MESSAGES: AiMessage[] = [
  {
    id: "msg-1",
    conversation_id: "conv-1",
    role: "user",
    content: "Can you explain why inferior MI is associated with RCA occlusion?",
    created_at: "2026-09-20T10:00:00Z",
  },
  {
    id: "msg-2",
    conversation_id: "conv-1",
    role: "assistant",
    content:
      "Great question! The right coronary artery (RCA) supplies the inferior wall of the left ventricle in approximately 70% of people (right-dominant circulation). When it is occluded, the inferior myocardium is deprived of blood flow, leading to ST elevation in leads II, III, and aVF — the leads that 'look at' the inferior wall.",
    created_at: "2026-09-20T10:00:30Z",
  },
  {
    id: "msg-3",
    conversation_id: "conv-1",
    role: "user",
    content: "What about in left-dominant circulation?",
    created_at: "2026-09-20T10:02:00Z",
  },
  {
    id: "msg-4",
    conversation_id: "conv-1",
    role: "assistant",
    content:
      "In left-dominant circulation (~10% of people), the left circumflex artery (LCx) gives rise to the posterior descending artery (PDA) and supplies the inferior wall. In these cases, LCx occlusion can cause inferior MI. This is why answering the question 'which artery caused the inferior MI' requires knowing the patient's coronary dominance.",
    created_at: "2026-09-20T10:02:40Z",
  },
  {
    id: "msg-5",
    conversation_id: "conv-2",
    role: "user",
    content: "Why can't bacteria develop resistance to penicillin by modifying the target?",
    created_at: "2026-09-22T14:00:00Z",
  },
  {
    id: "msg-6",
    conversation_id: "conv-2",
    role: "assistant",
    content:
      "Bacteria actually can — and do! The most common resistance mechanism is alteration of penicillin-binding proteins (PBPs). MRSA, for example, expresses PBP2a (encoded by mecA), which has very low affinity for all beta-lactams. Other mechanisms include beta-lactamase production (which hydrolyzes the beta-lactam ring) and reduced outer membrane permeability in Gram-negatives.",
    created_at: "2026-09-22T14:00:45Z",
  },
];

// ── Store object ──────────────────────────────────────────────────────────────

export interface MockStore {
  profiles: Profile[];
  access_requests: AccessRequest[];
  questions: Question[];
  question_attempts: QuestionAttempt[];
  mock_exams: MockExam[];
  mock_exam_questions: MockExamQuestion[];
  mock_answers: MockAnswer[];
  ai_conversations: AiConversation[];
  ai_messages: AiMessage[];
}

export function getMockStore(): MockStore {
  return {
    profiles: MOCK_PROFILES,
    access_requests: MOCK_ACCESS_REQUESTS,
    questions: MOCK_QUESTIONS,
    question_attempts: MOCK_QUESTION_ATTEMPTS,
    mock_exams: MOCK_EXAMS,
    mock_exam_questions: MOCK_EXAM_QUESTIONS,
    mock_answers: MOCK_ANSWERS,
    ai_conversations: MOCK_AI_CONVERSATIONS,
    ai_messages: MOCK_AI_MESSAGES,
  };
}
