import type { AnatomyNode, AnatomyContent } from '@/types/anatomy';

export function dbRowToNode(row: Record<string, unknown>): AnatomyNode {
  return {
    id: row.id as string,
    fmaId: (row.fma_id as number | null) ?? null,
    fmaUri: (row.fma_uri as string | null) ?? null,
    ta2Id: (row.ta2_id as number | null) ?? null,
    nameEn: row.name_en as string,
    nameLatin: (row.name_latin as string | null) ?? null,
    nameAr: (row.name_ar as string | null) ?? null,
    nameFma: (row.name_fma as string | null) ?? null,
    nameClinical: (row.name_clinical as string | null) ?? null,
    synonyms: (row.synonyms as string[]) ?? [],
    abbreviations: (row.abbreviations as string[]) ?? [],
    parentId: (row.parent_id as string | null) ?? null,
    level: row.level as AnatomyNode['level'],
    regionTags: (row.region_tags as string[]) ?? [],
    systemTags: (row.system_tags as string[]) ?? [],
    structureType: row.structure_type as AnatomyNode['structureType'],
    sex: row.sex as AnatomyNode['sex'],
    layer: (row.layer as AnatomyNode['layer']) ?? null,
    meshIds: (row.mesh_ids as string[]) ?? [],
    contentId: (row.content_id as string | null) ?? null,
    modelPending: (row.model_pending as boolean) ?? false,
    highlightColor: (row.highlight_color as string | null) ?? null,
    sortOrder: (row.sort_order as number) ?? 0,
  };
}

export function dbRowToContent(row: Record<string, unknown>): AnatomyContent {
  return {
    id: row.id as string,
    nodeId: row.node_id as string,
    description: (row.description as string | null) ?? null,
    functionText: (row.function_text as string | null) ?? null,
    locationRelations: (row.location_relations as AnatomyContent['locationRelations']) ?? null,
    arterialSupply: (row.arterial_supply as string | null) ?? null,
    venousDrainage: (row.venous_drainage as string | null) ?? null,
    lymphaticDrainage: (row.lymphatic_drainage as string | null) ?? null,
    innervation: (row.innervation as string | null) ?? null,
    embryologicalOrigin: (row.embryological_origin as string | null) ?? null,
    histology: (row.histology as string | null) ?? null,
    anatomicalVariations: (row.anatomical_variations as AnatomyContent['anatomicalVariations']) ?? [],
    clinicalCorrelations: (row.clinical_correlations as AnatomyContent['clinicalCorrelations']) ?? [],
    clinicalExamination: (row.clinical_examination as string | null) ?? null,
    proceduresSurgical: (row.procedures_surgical as string | null) ?? null,
    imagingAppearance: (row.imaging_appearance as AnatomyContent['imagingAppearance']) ?? null,
    examPoints: (row.exam_points as AnatomyContent['examPoints']) ?? [],
    sexDifferences: (row.sex_differences as string | null) ?? null,
    muscleOrigin: (row.muscle_origin as string | null) ?? null,
    muscleInsertion: (row.muscle_insertion as string | null) ?? null,
    muscleAction: (row.muscle_action as string | null) ?? null,
    muscleInnervation: (row.muscle_innervation as string | null) ?? null,
    muscleBloodSupply: (row.muscle_blood_supply as string | null) ?? null,
    muscleTest: (row.muscle_test as string | null) ?? null,
    boneParts: (row.bone_parts as string | null) ?? null,
    ossificationCentres: (row.ossification_centres as AnatomyContent['ossificationCentres']) ?? [],
    boneArticulations: (row.bone_articulations as string | null) ?? null,
    boneAttachments: (row.bone_attachments as string | null) ?? null,
    commonFractures: (row.common_fractures as AnatomyContent['commonFractures']) ?? [],
    jointType: (row.joint_type as string | null) ?? null,
    articularSurfaces: (row.articular_surfaces as string | null) ?? null,
    jointLigaments: (row.joint_ligaments as AnatomyContent['jointLigaments']) ?? [],
    jointMovements: (row.joint_movements as string | null) ?? null,
    stabilityFactors: (row.stability_factors as string | null) ?? null,
    commonInjuries: (row.common_injuries as string | null) ?? null,
    nerveRootValues: (row.nerve_root_values as string | null) ?? null,
    nerveCourse: (row.nerve_course as string | null) ?? null,
    nerveBranches: (row.nerve_branches as string | null) ?? null,
    nerveMotor: (row.nerve_motor as string | null) ?? null,
    nerveSensory: (row.nerve_sensory as string | null) ?? null,
    nerveLesion: (row.nerve_lesion as AnatomyContent['nerveLesion']) ?? [],
    vesselOrigin: (row.vessel_origin as string | null) ?? null,
    vesselCourse: (row.vessel_course as string | null) ?? null,
    vesselBranches: (row.vessel_branches as string | null) ?? null,
    vesselTerritory: (row.vessel_territory as string | null) ?? null,
    vesselAnastomoses: (row.vessel_anastomoses as string | null) ?? null,
    vesselClinical: (row.vessel_clinical as string | null) ?? null,
    organSurfaces: (row.organ_surfaces as string | null) ?? null,
    organBorders: (row.organ_borders as string | null) ?? null,
    organPeritoneal: (row.organ_peritoneal as string | null) ?? null,
    organSegments: (row.organ_segments as string | null) ?? null,
    referredPain: (row.referred_pain as string | null) ?? null,
    sources: (row.sources as AnatomyContent['sources']) ?? [],
    reviewStatus: row.review_status as AnatomyContent['reviewStatus'],
    reviewedBy: (row.reviewed_by as string | null) ?? null,
    reviewedAt: (row.reviewed_at as string | null) ?? null,
    approvedBy: (row.approved_by as string | null) ?? null,
    approvedAt: (row.approved_at as string | null) ?? null,
    version: row.version as number,
    createdAt: row.created_at as string,
    updatedAt: row.updated_at as string,
  };
}
